apiVersion: v2
name: kube-hunter
description: A Helm chart for the m9sweeper hunter and API
type: application
version: 0.0.1
appVersion: 0.0.1
maintainers:
  - name: Intelletive
    email: notify@intelletive.com
