{{- if eq .Values.cronjob.enabled false }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "kube-hunter.fullname" . }}
  labels:
    app: {{ template "kube-hunter.name" . }}
    chart: {{ template "kube-hunter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- with .Values.pod.annotations }}
  {{ toYaml . | indent 4 }}
{{- end }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      serviceAccount: {{ include "kube-hunter.name" . }}-sa
{{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
{{- end }}
      restartPolicy: Never
{{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["kube-hunter"]
          args:
            - "--pod"
            - "--report=json"
            - "--dispatch=http"
            {{- with .Values.customArguments }}
{{ toYaml . | indent 12 }}
            {{- end }}
          env:
          - name: KUBEHUNTER_HTTP_DISPATCH_URL
            value: "{{ .Values.dispatchUrl }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
  {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}:
  {{- end }}
{{- end }}
