{{- if .Values.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
rules:
  - apiGroups:
      - policy
    resourceNames:
      - {{ .Chart.Name }}
    resources:
      - podsecuritypolicies
    verbs:
      - use
{{- end }}
